### ISSUE TITLE
Make auto brightness with more levels/curves.

### ISSUE THREAD

**Issue by ghost** [mt6768-dev/android_device_xiaomi_mt6768-common#1]
@surblazer 

Current auto brightness / adaptive brightness on all `Redmi 9 Lancelot` custom roms that use backlight overlay from `android_device_xiaomi_mt6768-common` not as good as on the stock ROM or GSI.

I find it too dim/dark and difficult to read the screen as it always hits 0% when indoors.
And too bright when outdoors.

Meanwhile, on the stock ROM or GSI... auto brightness adapt better to different environment or conditions.
Never too dark or too bright.

On GSI.
Someone has converted `config_autoBrightnessLcdBacklightValues` from stock `11-bit number` to `8-bit number` for GSI overlay.
https://github.com/phhusson/vendor_hardware_overlay/pull/642
I believe the rest are from stock.

Is it possible if you change auto brightness overlay with more levels/curves like this?
https://github.com/phhusson/vendor_hardware_overlay/blob/pie/Xiaomi/Redmi9/res/values/config.xml

Thx.

**Comment by surblazer** [comment]
There was no need to ping me but okay, it's under review.

**Comment by surblazer** [comment]
Doesn't work on Android 13, DisplayManager crashing. We'll try to investigate that, but not sure
