### ISSUE TITLE
Reserve Extra Space in the System Partition

### ISSUE THREAD

**Issue by ghost** [mt6768-dev/android_device_xiaomi_mt6768-common#3]
Hi
First of all, I would like to thank you for your hard work.

I'm not sure if it's appropriate to report an issue here.
Because I installed **_LineageOS for microG_** on Redmi 9 (I know the ROM is not maintained by you).
And...
I tried to install [MinAddon-Playstore-Playstore-2.12.0-20230729205900.zip](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/download/2023.07.29/MinAddon-Playstore-Playstore-2.12.0-20230729205900.zip) or [MinMicroG-MinimalIAP-2.12.0-20230729205917.zip](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/download/2023.07.29/MinMicroG-MinimalIAP-2.12.0-20230729205917.zip) into the system partition using LOS recovery.

But there is a problem:

```
!!! FATAL ERROR: Not enough free space in your /mnt/system!

Stopping installation and Uninstalling...

Installation failed!

ERROR: recovery: Error in /sideload/package.zip (status 1)
```

Here is the log [last_log.txt](https://github.com/mt6768-dev/android_device_xiaomi_mt6768-common/files/12509010/last_log.txt).

The MinMicroG maintainer told me what the problem was and how to fix it [here](https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/56#issuecomment-1704333276)

What I'm trying to achieve is to use microG with **_unpatched/vanilla_** Play Store (yes it works fine now).
But i don't want to root my device.

So the only way is to flash MinMicroG into the system.
But as I explained above, there is a problem of not enough free space for it.

Can you fix it?
Thank you.

**Comment by leominerxd** [comment]
Not a kernel issue
